/**
 * This file was generated by @pikku/cli@0.12.15
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */


import type { WorkflowStepInput } from '../../pikku/workflows.gen.js'


export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type CreateAndNotifyWorkflowInput = { userId: string; title: string; priority: "low" | "medium" | "high"; dueDate?: string; }
export type CreateAndNotifyWorkflowOutput = { todo: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }; notificationSent: boolean; reminderScheduled: boolean; }
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type FetchOverdueTodosInput = { userId?: string; }
export type FetchOverdueTodosOutput = { userId: string; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; count: number; }
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type GraphStartTodoReviewWorkflowFetchOverdueOutput = { runId: string; }
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }
export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type PikkuRemoteInternalRPCInput = { rpcName: string; data?: any; }
export type PikkuWorkflowOrchestratorInput = { runId: string; }
export type PikkuWorkflowSleeperInput = { runId: string; stepId: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type ScheduleReminderInput = { todoId: string; userId: string; remindAt: string; }
export type ScheduleReminderOutput = { scheduled: boolean; jobId: string; }
export type SendNotificationInput = { userId: string; message: string; type?: "push" | "email" | "sms"; }
export type SendNotificationOutput = { sent: boolean; notificationId: string; }
export type SendOverdueSummaryInput = { userId: string; overdueCount: number; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; }
export type SendOverdueSummaryOutput = { sent: boolean; message: string; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type TodoAssistantOutput = {
    message: string;
    todos?: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[] | undefined;
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type WorkflowStartCreateAndNotifyWorkflowOutput = { runId: string; }
export type WorkflowStatusCreateAndNotifyWorkflowInput = { runId: string; }
export type WorkflowStatusCreateAndNotifyWorkflowOutput = { id: string; status: "completed" | "running" | "failed" | "cancelled"; output?: CreateAndNotifyWorkflowOutput; error?: { message?: string; }; }

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
  readonly 'listTodos': RPCHandler<ListTodosInput, ListTodosOutput>,
  readonly 'getTodo': RPCHandler<GetTodoInput, GetTodoOutput>,
  readonly 'createTodo': RPCHandler<CreateTodoInput, CreateTodoOutput>,
  readonly 'updateTodo': RPCHandler<UpdateTodoInput, UpdateTodoOutput>,
  readonly 'deleteTodo': RPCHandler<DeleteTodoInput, DeleteTodoOutput>,
  readonly 'completeTodo': RPCHandler<CompleteTodoInput, CompleteTodoOutput>,
  readonly 'onTestEvent': RPCHandler<OnTestEventInput, OnTestEventOutput>,
  readonly 'sendNotification': RPCHandler<SendNotificationInput, SendNotificationOutput>,
  readonly 'scheduleReminder': RPCHandler<ScheduleReminderInput, ScheduleReminderOutput>,
  readonly 'fetchOverdueTodos': RPCHandler<FetchOverdueTodosInput, FetchOverdueTodosOutput>,
  readonly 'sendOverdueSummary': RPCHandler<SendOverdueSummaryInput, SendOverdueSummaryOutput>,
  readonly 'rpcCaller': RPCHandler<RpcCallerInput, null>,
  readonly 'agentCaller': RPCHandler<AgentCallerInput, null>,
  readonly 'agentStreamCaller': RPCHandler<AgentStreamCallerInput, null>,
  readonly 'agentApproveCaller': RPCHandler<AgentApproveCallerInput, null>,
  readonly 'agentResumeCaller': RPCHandler<AgentResumeCallerInput, null>,
  readonly 'pikkuWorkflowWorker': RPCHandler<WorkflowStepInput, null>,
  readonly 'pikkuWorkflowOrchestrator': RPCHandler<PikkuWorkflowOrchestratorInput, null>,
  readonly 'pikkuWorkflowSleeper': RPCHandler<PikkuWorkflowSleeperInput, null>,
  readonly 'pikkuRemoteInternalRPC': RPCHandler<PikkuRemoteInternalRPCInput, null>,
};



// No addon packages, use RPCMap directly
export type FlattenedRPCMap = RPCMap


export type RPCInvoke = <Name extends keyof FlattenedRPCMap>(
  name: Name,
  data: FlattenedRPCMap[Name]['input']
) => Promise<FlattenedRPCMap[Name]['output']>

export type RPCRemote = <Name extends keyof FlattenedRPCMap>(
  name: Name,
  data: FlattenedRPCMap[Name]['input']
) => Promise<FlattenedRPCMap[Name]['output']>

import type { WorkflowMap } from '../workflow/pikku-workflow-map.gen.d.js'

import type { AgentMap } from '../agent/pikku-agent-map.gen.d.js'


type FlattenedAgentMap = AgentMap


import type { PikkuRPC } from '@pikku/core/rpc'

interface AIAgentInput {
  message: string
  threadId: string
  resourceId: string
}

export type TypedStartWorkflow = <Name extends keyof WorkflowMap>(
  name: Name,
  input: WorkflowMap[Name]['input'],
  options?: { startNode?: string }
) => Promise<{ runId: string }>

type TypedAgentRun = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput) => Promise<any>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput
    ) => Promise<{ runId: string; result: FlattenedAgentMap[Name]['output']; usage: { inputTokens: number; outputTokens: number } }>

type TypedAgentStream = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput, options?: { requiresToolApproval?: 'all' | 'explicit' | false }) => Promise<void>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput,
      options?: { requiresToolApproval?: 'all' | 'explicit' | false }
    ) => Promise<void>

export type TypedPikkuRPC = PikkuRPC<RPCInvoke, RPCRemote, TypedStartWorkflow, TypedAgentRun, TypedAgentStream>
  