/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */



export type LoginInput = {
    username: string;
    password: string;
}
export type LoginOutput = {
    token: string;
    user: {
        id: string;
        username: string;
        email: string;
    };
}
export type GetMeInput = {}
export type GetMeOutput = {
    user: {
        id: string;
        username: string;
        email: string;
    };
}
export type LogoutInput = {}
export type LogoutOutput = {
    success: boolean;
}
export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: string | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: string | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type SendNotificationInput = { userId: string; message: string; type?: "push" | "email" | "sms"; }
export type SendNotificationOutput = { sent: boolean; notificationId: string; }
export type ScheduleReminderInput = { todoId: string; userId: string; remindAt: string; }
export type ScheduleReminderOutput = { scheduled: boolean; jobId: string; }
export type CreateAndNotifyWorkflowInput = { userId: string; title: string; priority: "low" | "medium" | "high"; dueDate?: string; }
export type CreateAndNotifyWorkflowOutput = { todo: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }; notificationSent: boolean; reminderScheduled: boolean; }
export type FetchOverdueTodosInput = { userId?: string; }
export type FetchOverdueTodosOutput = { userId: string; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; count: number; }
export type SendOverdueSummaryInput = { userId: string; overdueCount: number; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; }
export type SendOverdueSummaryOutput = { sent: boolean; message: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L31C9Input = { rpcName: string; }
export type StartCreateAndNotifyWorkflowInput = { userId: string; title: string; priority: "low" | "medium" | "high"; dueDate?: string; }
export type StartCreateAndNotifyWorkflowOutput = { runId: string; }

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
  readonly 'startCreateAndNotifyWorkflow': RPCHandler<StartCreateAndNotifyWorkflowInput, StartCreateAndNotifyWorkflowOutput>,
};



// No external packages, use RPCMap directly
export type FlattenedRPCMap = RPCMap


export type RPCInvoke = <Name extends keyof FlattenedRPCMap>(
  name: Name,
  data: FlattenedRPCMap[Name]['input'],
  options?: {
    location?: 'local' | 'remote' | 'auto'
  }
) => Promise<FlattenedRPCMap[Name]['output']>

// Import WorkflowMap for workflow typing
import type { WorkflowMap } from '../workflow/pikku-workflow-map.gen.js'

export type TypedPikkuRPC = {
  depth: number;
  global: boolean;
  invoke: RPCInvoke;
  invokeExposed: (name: string, data: any) => Promise<any>;
  startWorkflow: <Name extends keyof WorkflowMap>(
    name: Name,
    input: WorkflowMap[Name]['input']
  ) => Promise<{ runId: string }>;
}
  