/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState } from '@pikku/core/internal'
import { CLIMeta } from '@pikku/core/cli'
import metaData from './pikku-cli-wirings-meta.gen.json' with { type: 'json' }
pikkuState(null, 'cli', 'meta', metaData as CLIMeta)