/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * Workflow queue workers for orchestration
 */
import { pikkuSessionlessFunc, wireQueueWorker } from '../../pikku-gen/pikku-types.gen.js'

export type WorkflowStepInput = {
  runId: string
  stepName: string
  rpcName: string
  data: any
}

export const pikkuWorkflowWorker = pikkuSessionlessFunc<WorkflowStepInput, void>({
  func: async ({ workflowService }, { runId, stepName, rpcName, data }, { rpc }) => {
    await workflowService!.executeWorkflowStep(runId, stepName, rpcName, data, rpc)
  }
})

export const pikkuWorkflowOrchestrator = pikkuSessionlessFunc<{ runId: string }, void>({
  func: async ({ workflowService }, { runId }, { rpc }) => {
    await workflowService!.orchestrateWorkflow(runId, rpc)
  }
})

export const pikkuWorkflowSleeper = pikkuSessionlessFunc<{ runId: string, stepId: string }, void>({
  func: async ({ workflowService }, { runId, stepId }) => {
    await workflowService!.executeWorkflowSleepCompleted(runId, stepId)
  },
  internal: true,
})

export const pikkuRemoteInternalRPC = pikkuSessionlessFunc<{ rpcName: string, data?: any }, any>({
  func: async (_services, { rpcName, data }, { rpc }) => {
    return await (rpc.invoke as any)(rpcName, data)
  },
  internal: true,
})

wireQueueWorker({ queueName: 'pikku-workflow-step-worker', func: pikkuWorkflowWorker })
wireQueueWorker({ queueName: 'pikku-workflow-orchestrator', func: pikkuWorkflowOrchestrator })
wireQueueWorker({ queueName: 'pikku-remote-internal-rpc', func: pikkuRemoteInternalRPC })
