/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState } from '@pikku/core/internal'
import type { MCPResourceMeta, MCPToolMeta, MCPPromptMeta } from '@pikku/core/mcp'
import metaData from './pikku-mcp-wirings-meta.gen.json' with { type: 'json' }
pikkuState(null, 'mcp', 'resourcesMeta', metaData.resourcesMeta as MCPResourceMeta)
pikkuState(null, 'mcp', 'toolsMeta', metaData.toolsMeta as MCPToolMeta)
pikkuState(null, 'mcp', 'promptsMeta', metaData.promptsMeta as MCPPromptMeta)