/**
 * This file was generated by @pikku/cli@0.12.15
 */
/**
 * Workflow type map with input/output types for each workflow
 */




export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type CreateAndNotifyWorkflowInput = { userId: string; title: string; priority: "low" | "medium" | "high"; dueDate?: string; }
export type CreateAndNotifyWorkflowOutput = { todo: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }; notificationSent: boolean; reminderScheduled: boolean; }
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type FetchOverdueTodosInput = { userId?: string; }
export type FetchOverdueTodosOutput = { userId: string; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; count: number; }
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type GraphStartTodoReviewWorkflowFetchOverdueOutput = { runId: string; }
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }
export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type PikkuRemoteInternalRPCInput = { rpcName: string; data?: any; }
export type PikkuWorkflowOrchestratorInput = { runId: string; }
export type PikkuWorkflowSleeperInput = { runId: string; stepId: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type ScheduleReminderInput = { todoId: string; userId: string; remindAt: string; }
export type ScheduleReminderOutput = { scheduled: boolean; jobId: string; }
export type SendNotificationInput = { userId: string; message: string; type?: "push" | "email" | "sms"; }
export type SendNotificationOutput = { sent: boolean; notificationId: string; }
export type SendOverdueSummaryInput = { userId: string; overdueCount: number; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; }
export type SendOverdueSummaryOutput = { sent: boolean; message: string; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type TodoAssistantOutput = {
    message: string;
    todos?: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[] | undefined;
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type WorkflowStartCreateAndNotifyWorkflowOutput = { runId: string; }
export type WorkflowStatusCreateAndNotifyWorkflowInput = { runId: string; }
export type WorkflowStatusCreateAndNotifyWorkflowOutput = { id: string; status: "completed" | "running" | "failed" | "cancelled"; output?: CreateAndNotifyWorkflowOutput; error?: { message?: string; }; }

interface WorkflowHandler<I, O> {
    input: I;
    output: O;
}

interface GraphNodeHandler<I> {
    input: I;
}

export type WorkflowMap = {
  readonly 'createAndNotifyWorkflow': WorkflowHandler<CreateAndNotifyWorkflowInput, CreateAndNotifyWorkflowOutput>,
};

export type GraphsMap = {
  readonly 'todoReviewWorkflow': {
    readonly 'fetchOverdue': GraphNodeHandler<FetchOverdueTodosInput>,
    readonly 'sendSummary': GraphNodeHandler<SendOverdueSummaryInput>,
  },
  readonly 'createAndNotifyWorkflow': {
    readonly 'Create todo': GraphNodeHandler<CreateTodoInput>,
    readonly 'Send high priority notification': GraphNodeHandler<SendNotificationInput>,
    readonly 'Schedule reminder': GraphNodeHandler<ScheduleReminderInput>,
  },
};

export type WorkflowClient<Name extends keyof WorkflowMap> = {
  start: (input: WorkflowMap[Name]['input']) => Promise<{ runId: string }>;
  getRun: <output extends keyof WorkflowMap[Name]>(runId: string) => Promise<WorkflowMap[Name][output]>;
  cancelRun: (runId: string) => Promise<boolean>;
}

export type TypedWorkflowClients = {
  [Name in keyof WorkflowMap]: WorkflowClient<Name>;
}
