/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { addWorkflow } from '@pikku/core/workflow'
import './pikku-workflow-wirings-meta.gen.js'
import { createAndNotifyWorkflow } from '../../src/functions/workflow.functions.js'

addWorkflow('createAndNotifyWorkflow', createAndNotifyWorkflow)

export type WorkflowNames = 'todoReviewWorkflow' | 'createAndNotifyWorkflow'