/**
 * This file was generated by @pikku/cli@0.11.3
 */
import { pikkuState } from '@pikku/core'
import type { SerializedWorkflowGraphs } from '@pikku/inspector/workflow-graph'

import createAndNotifyWorkflowMeta from './meta/createAndNotifyWorkflow.gen.json' with { type: 'json' }

const workflowsMeta = {
  'createAndNotifyWorkflow': createAndNotifyWorkflowMeta,
} as SerializedWorkflowGraphs

pikkuState(null, 'workflows', 'meta', workflowsMeta)