/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState } from '@pikku/core/internal'
import type { SerializedWorkflowGraphs } from '@pikku/inspector/workflow-graph'

import createAndNotifyWorkflowMeta from './meta/createAndNotifyWorkflow.gen.json' with { type: 'json' }
import todoReviewWorkflowMeta from './meta/todoReviewWorkflow.gen.json' with { type: 'json' }

const workflowsMeta = {
  'createAndNotifyWorkflow': createAndNotifyWorkflowMeta,
  'todoReviewWorkflow': todoReviewWorkflowMeta,
} as SerializedWorkflowGraphs

pikkuState(null, 'workflows', 'meta', workflowsMeta)