/**
 * This file was generated by @pikku/cli@0.11.3
 */
import { addWorkflow, addWorkflowGraph } from '@pikku/core/workflow'
import './pikku-workflow-wirings-meta.gen.js'
import { createAndNotifyWorkflow } from '../../src/functions/workflow.functions.js'
import { todoReviewWorkflow } from '../../src/wirings/workflow.wiring.js'

addWorkflow('createAndNotifyWorkflow', createAndNotifyWorkflow)
addWorkflowGraph('todoReviewWorkflow', todoReviewWorkflow)

export type WorkflowNames = 'createAndNotifyWorkflow' | 'todoReviewWorkflow'