/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { TypedSecretService as CoreTypedSecretService, type CredentialMeta } from '@pikku/core/services'
import type { SecretService } from '@pikku/core/services'

export interface CredentialsMap {

}

export type SecretId = keyof CredentialsMap

const CREDENTIALS_META: Record<string, CredentialMeta> = {

}

export class TypedSecretService extends CoreTypedSecretService<CredentialsMap> {
  constructor(secrets: SecretService) {
    super(secrets, CREDENTIALS_META)
  }
}
