/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { TypedVariablesService as CoreTypedVariablesService, type VariableMeta } from '@pikku/core/services'
import type { VariablesService } from '@pikku/core/services'

export interface VariablesMap {

}

export type VariableId = keyof VariablesMap

const VARIABLES_META: Record<string, VariableMeta> = {

}

export class TypedVariablesService extends CoreTypedVariablesService<VariablesMap> {
  constructor(variables: VariablesService) {
    super(variables, VARIABLES_META)
  }
}
