/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState as __pikkuState } from '@pikku/core/internal'
try {
  const { fileURLToPath: __fileURLToPath } = await import('url')
  const { dirname: __dirname } = await import('path')
  __pikkuState(null, 'package', 'metaDir', __dirname(__fileURLToPath(import.meta.url)))
} catch {}
import './agent/pikku-agent-wirings-meta.gen.js'
import './rpc/pikku-rpc-wirings-meta.internal.gen.js'
import './http/pikku-http-wirings-meta.gen.js'
import './scheduler/pikku-schedulers-wirings-meta.gen.js'
import './trigger/pikku-trigger-wirings-meta.gen.js'
import './trigger/pikku-trigger-sources-meta.gen.js'
import './function/pikku-functions-meta.gen.js'
import './queue/pikku-queue-workers-wirings-meta.gen.js'
import './channel/pikku-channels-meta.gen.js'
import './mcp/pikku-mcp-wirings-meta.gen.js'
import './cli/pikku-cli-wirings-meta.gen.js'
import './middleware/pikku-middleware.gen.js'
import './agent/pikku-agent-wirings.gen.js'
import './schemas/register.gen.js'
import './http/pikku-http-wirings.gen.js'
import './scheduler/pikku-schedulers-wirings.gen.js'
import './trigger/pikku-trigger-wirings.gen.js'
import './function/pikku-functions.gen.js'
import './workflow/pikku-workflow-wirings.gen.js'
import './queue/pikku-queue-workers-wirings.gen.js'
import './channel/pikku-channels.gen.js'
import './mcp/pikku-mcp-wirings.gen.js'
import './cli/pikku-cli-wirings.gen.js'