/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState } from '@pikku/core/internal'
import type { AIAgentMeta } from '@pikku/core/ai-agent'
import metaData from './pikku-agent-wirings-meta.gen.json' with { type: 'json' }
pikkuState(null, 'agent', 'agentsMeta', metaData.agentsMeta as AIAgentMeta)