/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { addAIAgent } from '@pikku/core/ai-agent'
import './pikku-agent-wirings-meta.gen.js'
import { dailyPlanner } from '../../src/functions/agent.functions.js'
import { mainRouter } from '../../src/functions/agent.functions.js'
import { todoAssistant } from '../../src/functions/agent.functions.js'

addAIAgent('dailyPlanner', dailyPlanner)
addAIAgent('mainRouter', mainRouter)
addAIAgent('todoAssistant', todoAssistant)