/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState } from '@pikku/core/internal'
import { TriggerMeta } from '@pikku/core/trigger'
import metaData from './pikku-trigger-wirings-meta.gen.json' with { type: 'json' }

pikkuState(null, 'trigger', 'meta', metaData as TriggerMeta)

export type TriggerNames = 'test-event'