/**
 * This file was generated by @pikku/cli@0.12.15
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */





export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type CreateAndNotifyWorkflowInput = { userId: string; title: string; priority: "low" | "medium" | "high"; dueDate?: string; }
export type CreateAndNotifyWorkflowOutput = { todo: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }; notificationSent: boolean; reminderScheduled: boolean; }
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type FetchOverdueTodosInput = { userId?: string; }
export type FetchOverdueTodosOutput = { userId: string; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; count: number; }
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type GraphStartTodoReviewWorkflowFetchOverdueOutput = { runId: string; }
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }
export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type PikkuRemoteInternalRPCInput = { rpcName: string; data?: any; }
export type PikkuWorkflowOrchestratorInput = { runId: string; }
export type PikkuWorkflowSleeperInput = { runId: string; stepId: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type ScheduleReminderInput = { todoId: string; userId: string; remindAt: string; }
export type ScheduleReminderOutput = { scheduled: boolean; jobId: string; }
export type SendNotificationInput = { userId: string; message: string; type?: "push" | "email" | "sms"; }
export type SendNotificationOutput = { sent: boolean; notificationId: string; }
export type SendOverdueSummaryInput = { userId: string; overdueCount: number; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; }
export type SendOverdueSummaryOutput = { sent: boolean; message: string; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type TodoAssistantOutput = {
    message: string;
    todos?: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[] | undefined;
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type WorkflowStartCreateAndNotifyWorkflowOutput = { runId: string; }
export type WorkflowStatusCreateAndNotifyWorkflowInput = { runId: string; }
export type WorkflowStatusCreateAndNotifyWorkflowOutput = { id: string; status: "completed" | "running" | "failed" | "cancelled"; output?: CreateAndNotifyWorkflowOutput; error?: { message?: string; }; }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type FetchOverdueTodosInputBody = FetchOverdueTodosInput & {}
export type HttpOptionsRpcRpcNameInputParams = Pick<HttpOptionsRpcRpcNameInput, 'rpcName'> & {}
export type HttpOptionsRpcRpcNameInputBody = Omit<HttpOptionsRpcRpcNameInput, 'rpcName'> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}
export type ListTodosInputBody = ListTodosInput & {}
export type GetTodoInputParams = Pick<GetTodoInput, 'id'> & {}
export type GetTodoInputBody = Omit<GetTodoInput, 'id'> & {}
export type CreateTodoInputBody = CreateTodoInput & {}
export type UpdateTodoInputParams = Pick<UpdateTodoInput, 'id'> & {}
export type UpdateTodoInputBody = Omit<UpdateTodoInput, 'id'> & {}
export type DeleteTodoInputParams = Pick<DeleteTodoInput, 'id'> & {}
export type DeleteTodoInputBody = Omit<DeleteTodoInput, 'id'> & {}
export type CompleteTodoInputParams = Pick<CompleteTodoInput, 'id'> & {}
export type CompleteTodoInputBody = Omit<CompleteTodoInput, 'id'> & {}
export type CreateAndNotifyWorkflowInputBody = CreateAndNotifyWorkflowInput & {}
export type WorkflowStatusCreateAndNotifyWorkflowInputParams = Pick<WorkflowStatusCreateAndNotifyWorkflowInput, 'runId'> & {}
export type WorkflowStatusCreateAndNotifyWorkflowInputBody = Omit<WorkflowStatusCreateAndNotifyWorkflowInput, 'runId'> & {}
export type AgentCallerInputParams = Pick<AgentCallerInput, 'agentName'> & {}
export type AgentCallerInputBody = Omit<AgentCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputParams = Pick<AgentStreamCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputBody = Omit<AgentStreamCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputParams = Pick<AgentApproveCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputBody = Omit<AgentApproveCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputParams = Pick<AgentResumeCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputBody = Omit<AgentResumeCallerInput, 'agentName'> & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/todos': {
    readonly GET: HTTPWiringHandler<ListTodosInput, ListTodosOutput>,
    readonly POST: HTTPWiringHandler<CreateTodoInput, CreateTodoOutput>,
  },
  readonly '/todos/:id': {
    readonly GET: HTTPWiringHandler<GetTodoInput, GetTodoOutput>,
    readonly PUT: HTTPWiringHandler<UpdateTodoInput, UpdateTodoOutput>,
    readonly DELETE: HTTPWiringHandler<DeleteTodoInput, DeleteTodoOutput>,
  },
  readonly '/workflow/status/:runId': {
    readonly GET: HTTPWiringHandler<WorkflowStatusCreateAndNotifyWorkflowInput, WorkflowStatusCreateAndNotifyWorkflowOutput>,
  },
  readonly '/workflow/review': {
    readonly POST: HTTPWiringHandler<FetchOverdueTodosInput, GraphStartTodoReviewWorkflowFetchOverdueOutput>,
  },
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<HttpOptionsRpcRpcNameInput, unknown>,
  },
  readonly '/todos/:id/complete': {
    readonly POST: HTTPWiringHandler<CompleteTodoInput, CompleteTodoOutput>,
  },
  readonly '/workflow/create-todo': {
    readonly POST: HTTPWiringHandler<CreateTodoInput, WorkflowStartCreateAndNotifyWorkflowOutput>,
  },
  readonly '/workflow/run-todo': {
    readonly POST: HTTPWiringHandler<CreateTodoInput, CreateAndNotifyWorkflowOutput>,
  },
  readonly '/rpc/agent/:agentName': {
    readonly POST: HTTPWiringHandler<AgentCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/stream': {
    readonly POST: HTTPWiringHandler<AgentStreamCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/approve': {
    readonly POST: HTTPWiringHandler<AgentApproveCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/resume': {
    readonly POST: HTTPWiringHandler<AgentResumeCallerInput, null>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  