/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState } from '@pikku/core/internal'
import { QueueWorkersMeta } from '@pikku/core/queue'
import metaData from './pikku-queue-workers-wirings-meta.gen.json' with { type: 'json' }

pikkuState(null, 'queue', 'meta', metaData as QueueWorkersMeta)