/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */

import type { WorkflowStepInput } from '../../src/workflows/pikku.workflows.gen.js'

export type LoginInput = unknown
export type LoginOutput = unknown
export type GetMeInput = unknown
export type GetMeOutput = unknown
export type LogoutInput = unknown
export type LogoutOutput = unknown
export type ListTodosInput = unknown
export type ListTodosOutput = unknown
export type GetTodoInput = unknown
export type GetTodoOutput = unknown
export type CreateTodoInput = unknown
export type CreateTodoOutput = unknown
export type UpdateTodoInput = unknown
export type UpdateTodoOutput = unknown
export type DeleteTodoInput = unknown
export type DeleteTodoOutput = unknown
export type CompleteTodoInput = unknown
export type CompleteTodoOutput = unknown
export type SendNotificationInput = { userId: string; message: string; type?: "push" | "email" | "sms"; }
export type SendNotificationOutput = { sent: boolean; notificationId: string; }
export type ScheduleReminderInput = { todoId: string; userId: string; remindAt: string; }
export type ScheduleReminderOutput = { scheduled: boolean; jobId: string; }
export type CreateAndNotifyWorkflowInput = { userId: string; title: string; priority: "low" | "medium" | "high"; dueDate?: string; }
export type CreateAndNotifyWorkflowOutput = { todo: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }; notificationSent: boolean; reminderScheduled: boolean; }
export type FetchOverdueTodosInput = { userId?: string; }
export type FetchOverdueTodosOutput = { userId: string; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; count: number; }
export type SendOverdueSummaryInput = { userId: string; overdueCount: number; todos: { id: string; userId: string; title: string; completed: boolean; priority: "low" | "medium" | "high"; tags: string[]; createdAt: string; updatedAt: string; description?: string; dueDate?: string; }[]; }
export type SendOverdueSummaryOutput = { sent: boolean; message: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L32C9Input = { rpcName: string; }
export type StartCreateAndNotifyWorkflowInput = { userId: string; title: string; priority: "low" | "medium" | "high"; dueDate?: string; }
export type StartCreateAndNotifyWorkflowOutput = { runId: string; }
export type PikkuWorkflowOrchestratorInput = { runId: string; }
export type PikkuWorkflowSleeperInput = { runId: string; stepId: string; }
export type PikkuRemoteInternalRPCInput = { rpcName: string; data?: any; }

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
    input: I;
    output: O;
}

export type QueueMap = {
  readonly 'pikku-workflow-step-worker': QueueHandler<WorkflowStepInput, null>,
  readonly 'pikku-workflow-orchestrator': QueueHandler<PikkuWorkflowOrchestratorInput, null>,
  readonly 'pikku-remote-internal-rpc': QueueHandler<PikkuRemoteInternalRPCInput, null>,
};


type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd;
  getJob: QueueGetJob;
}
  