/**
 * This file was generated by @pikku/cli@0.11.3
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { createTodo } from '../../src/functions/todos.functions.js'
import { greet } from '../../src/functions/remote-rpc.functions.js'
import { onTestEvent } from '../../src/functions/trigger.functions.js'
import { scheduleReminder } from '../../src/functions/workflow.functions.js'
import { sendNotification } from '../../src/functions/workflow.functions.js'

addFunction('createTodo', createTodo)
addFunction('greet', greet)
addFunction('onTestEvent', onTestEvent)
addFunction('scheduleReminder', scheduleReminder)
addFunction('sendNotification', sendNotification)