/**
 * This file was generated by @pikku/cli@0.11.3
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { createTodo } from '../../src/functions/todos.functions.js'
import { scheduleReminder } from '../../src/functions/workflow.functions.js'
import { sendNotification } from '../../src/functions/workflow.functions.js'
import { startCreateAndNotifyWorkflow } from '../../src/wirings/workflow.wiring.js'

addFunction('createTodo', createTodo)
addFunction('scheduleReminder', scheduleReminder)
addFunction('sendNotification', sendNotification)
addFunction('startCreateAndNotifyWorkflow', startCreateAndNotifyWorkflow)