/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { pikkuState } from '@pikku/core/internal'
import type { FunctionsMeta } from '@pikku/core'
import metaData from './pikku-functions-meta.gen.json' with { type: 'json' }
pikkuState(null, 'function', 'meta', metaData as FunctionsMeta)