/**
 * This file was generated by @pikku/cli@0.12.15
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { completeTodo } from '../../src/functions/todos.functions.js'
import { createTodo } from '../../src/functions/todos.functions.js'
import { deleteTodo } from '../../src/functions/todos.functions.js'
import { fetchOverdueTodos } from '../../src/functions/workflow.functions.js'
import { listTodos } from '../../src/functions/todos.functions.js'
import { onTestEvent } from '../../src/functions/trigger.functions.js'
import { pikkuRemoteInternalRPC } from '../../pikku/workflows.gen.js'
import { pikkuWorkflowSleeper } from '../../pikku/workflows.gen.js'
import { scheduleReminder } from '../../src/functions/workflow.functions.js'
import { sendNotification } from '../../src/functions/workflow.functions.js'
import { sendOverdueSummary } from '../../src/functions/workflow.functions.js'

addFunction('completeTodo', completeTodo)
addFunction('createTodo', createTodo)
addFunction('deleteTodo', deleteTodo)
addFunction('fetchOverdueTodos', fetchOverdueTodos)
addFunction('listTodos', listTodos)
addFunction('onTestEvent', onTestEvent)
addFunction('pikkuRemoteInternalRPC', pikkuRemoteInternalRPC)
addFunction('pikkuWorkflowSleeper', pikkuWorkflowSleeper)
addFunction('scheduleReminder', scheduleReminder)
addFunction('sendNotification', sendNotification)
addFunction('sendOverdueSummary', sendOverdueSummary)