/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { addSchema } from '@pikku/core/schema'

import * as WorkflowStepInput from './schemas/WorkflowStepInput.schema.json' with { type: 'json' }
addSchema('WorkflowStepInput', WorkflowStepInput)


import * as PikkuWorkflowOrchestratorInput from './schemas/PikkuWorkflowOrchestratorInput.schema.json' with { type: 'json' }
addSchema('PikkuWorkflowOrchestratorInput', PikkuWorkflowOrchestratorInput)


import * as PikkuWorkflowSleeperInput from './schemas/PikkuWorkflowSleeperInput.schema.json' with { type: 'json' }
addSchema('PikkuWorkflowSleeperInput', PikkuWorkflowSleeperInput)


import * as PikkuRemoteInternalRPCInput from './schemas/PikkuRemoteInternalRPCInput.schema.json' with { type: 'json' }
addSchema('PikkuRemoteInternalRPCInput', PikkuRemoteInternalRPCInput)


import * as ListTodosInput from './schemas/ListTodosInput.schema.json' with { type: 'json' }
addSchema('ListTodosInput', ListTodosInput)


import * as ListTodosOutput from './schemas/ListTodosOutput.schema.json' with { type: 'json' }
addSchema('ListTodosOutput', ListTodosOutput)


import * as GetTodoInput from './schemas/GetTodoInput.schema.json' with { type: 'json' }
addSchema('GetTodoInput', GetTodoInput)


import * as GetTodoOutput from './schemas/GetTodoOutput.schema.json' with { type: 'json' }
addSchema('GetTodoOutput', GetTodoOutput)


import * as CreateTodoInput from './schemas/CreateTodoInput.schema.json' with { type: 'json' }
addSchema('CreateTodoInput', CreateTodoInput)


import * as CreateTodoOutput from './schemas/CreateTodoOutput.schema.json' with { type: 'json' }
addSchema('CreateTodoOutput', CreateTodoOutput)


import * as UpdateTodoInput from './schemas/UpdateTodoInput.schema.json' with { type: 'json' }
addSchema('UpdateTodoInput', UpdateTodoInput)


import * as UpdateTodoOutput from './schemas/UpdateTodoOutput.schema.json' with { type: 'json' }
addSchema('UpdateTodoOutput', UpdateTodoOutput)


import * as DeleteTodoInput from './schemas/DeleteTodoInput.schema.json' with { type: 'json' }
addSchema('DeleteTodoInput', DeleteTodoInput)


import * as DeleteTodoOutput from './schemas/DeleteTodoOutput.schema.json' with { type: 'json' }
addSchema('DeleteTodoOutput', DeleteTodoOutput)


import * as CompleteTodoInput from './schemas/CompleteTodoInput.schema.json' with { type: 'json' }
addSchema('CompleteTodoInput', CompleteTodoInput)


import * as CompleteTodoOutput from './schemas/CompleteTodoOutput.schema.json' with { type: 'json' }
addSchema('CompleteTodoOutput', CompleteTodoOutput)


import * as TestEventTriggerInput from './schemas/TestEventTriggerInput.schema.json' with { type: 'json' }
addSchema('TestEventTriggerInput', TestEventTriggerInput)


import * as TestEventTriggerOutput from './schemas/TestEventTriggerOutput.schema.json' with { type: 'json' }
addSchema('TestEventTriggerOutput', TestEventTriggerOutput)


import * as OnTestEventInput from './schemas/OnTestEventInput.schema.json' with { type: 'json' }
addSchema('OnTestEventInput', OnTestEventInput)


import * as OnTestEventOutput from './schemas/OnTestEventOutput.schema.json' with { type: 'json' }
addSchema('OnTestEventOutput', OnTestEventOutput)


import * as SendNotificationInput from './schemas/SendNotificationInput.schema.json' with { type: 'json' }
addSchema('SendNotificationInput', SendNotificationInput)


import * as SendNotificationOutput from './schemas/SendNotificationOutput.schema.json' with { type: 'json' }
addSchema('SendNotificationOutput', SendNotificationOutput)


import * as ScheduleReminderInput from './schemas/ScheduleReminderInput.schema.json' with { type: 'json' }
addSchema('ScheduleReminderInput', ScheduleReminderInput)


import * as ScheduleReminderOutput from './schemas/ScheduleReminderOutput.schema.json' with { type: 'json' }
addSchema('ScheduleReminderOutput', ScheduleReminderOutput)


import * as CreateAndNotifyWorkflowInput from './schemas/CreateAndNotifyWorkflowInput.schema.json' with { type: 'json' }
addSchema('CreateAndNotifyWorkflowInput', CreateAndNotifyWorkflowInput)


import * as CreateAndNotifyWorkflowOutput from './schemas/CreateAndNotifyWorkflowOutput.schema.json' with { type: 'json' }
addSchema('CreateAndNotifyWorkflowOutput', CreateAndNotifyWorkflowOutput)


import * as FetchOverdueTodosInput from './schemas/FetchOverdueTodosInput.schema.json' with { type: 'json' }
addSchema('FetchOverdueTodosInput', FetchOverdueTodosInput)


import * as FetchOverdueTodosOutput from './schemas/FetchOverdueTodosOutput.schema.json' with { type: 'json' }
addSchema('FetchOverdueTodosOutput', FetchOverdueTodosOutput)


import * as SendOverdueSummaryInput from './schemas/SendOverdueSummaryInput.schema.json' with { type: 'json' }
addSchema('SendOverdueSummaryInput', SendOverdueSummaryInput)


import * as SendOverdueSummaryOutput from './schemas/SendOverdueSummaryOutput.schema.json' with { type: 'json' }
addSchema('SendOverdueSummaryOutput', SendOverdueSummaryOutput)


import * as GraphStartTodoReviewWorkflowFetchOverdueOutput from './schemas/GraphStartTodoReviewWorkflowFetchOverdueOutput.schema.json' with { type: 'json' }
addSchema('GraphStartTodoReviewWorkflowFetchOverdueOutput', GraphStartTodoReviewWorkflowFetchOverdueOutput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)


import * as HttpOptionsRpcRpcNameInput from './schemas/HttpOptionsRpcRpcNameInput.schema.json' with { type: 'json' }
addSchema('HttpOptionsRpcRpcNameInput', HttpOptionsRpcRpcNameInput)


import * as WorkflowStartCreateAndNotifyWorkflowOutput from './schemas/WorkflowStartCreateAndNotifyWorkflowOutput.schema.json' with { type: 'json' }
addSchema('WorkflowStartCreateAndNotifyWorkflowOutput', WorkflowStartCreateAndNotifyWorkflowOutput)


import * as WorkflowStatusCreateAndNotifyWorkflowInput from './schemas/WorkflowStatusCreateAndNotifyWorkflowInput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusCreateAndNotifyWorkflowInput', WorkflowStatusCreateAndNotifyWorkflowInput)


import * as WorkflowStatusCreateAndNotifyWorkflowOutput from './schemas/WorkflowStatusCreateAndNotifyWorkflowOutput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusCreateAndNotifyWorkflowOutput', WorkflowStatusCreateAndNotifyWorkflowOutput)


import * as AgentCallerInput from './schemas/AgentCallerInput.schema.json' with { type: 'json' }
addSchema('AgentCallerInput', AgentCallerInput)


import * as AgentStreamCallerInput from './schemas/AgentStreamCallerInput.schema.json' with { type: 'json' }
addSchema('AgentStreamCallerInput', AgentStreamCallerInput)


import * as AgentApproveCallerInput from './schemas/AgentApproveCallerInput.schema.json' with { type: 'json' }
addSchema('AgentApproveCallerInput', AgentApproveCallerInput)


import * as AgentResumeCallerInput from './schemas/AgentResumeCallerInput.schema.json' with { type: 'json' }
addSchema('AgentResumeCallerInput', AgentResumeCallerInput)


import * as TodoAssistantOutput from './schemas/TodoAssistantOutput.schema.json' with { type: 'json' }
addSchema('TodoAssistantOutput', TodoAssistantOutput)
