/**
 * This file was generated by @pikku/cli@0.12.15
 */
import type { FlattenedRPCMap } from '../rpc/pikku-rpc-wirings-map.internal.gen.js'

export type NodeCategory = never

export type NodeRPCName = keyof FlattenedRPCMap
